---
  - name: Fix host static IP after reboot
    community.windows.win_scheduled_task:
      name: Set static
      description: open command prompt
      actions:
      - path: cmd
        arguments: /c netsh interface ipv4 set address name="{{ ethernet_adapter }}" static {{host_ip}} 255.255.255.0 10.10.10.1
      triggers:
      - type: boot
      username: SYSTEM
      state: present
      enabled: yes

  - name: Change DNS
    win_dns_client:
      adapter_names: "{{ ethernet_adapter }}"
      ipv4_addresses:
        - "{{dns_server}}"
        - 1.1.1.1
    register: dns_setup

  - name: Reboot server after change network configurations
    win_shell: shutdown /r /t 0
    async: 1
    poll: 0
    failed_when: false
    when: dns_setup.changed

  - name: Waiting 2 minutes for the machine bootup
    pause:
      minutes: 2

  - name: Cambiar adaptador de red a NATSwitch en Hyper-V
    ansible.builtin.shell: >
      /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -Command
      "Connect-VMNetworkAdapter -VMName '{{ vm_name }}' -SwitchName 'NATSwitch'"
    delegate_to: localhost