---
- hosts: krillin
  gather_facts: True
  vars:
    ansible_winrm_transport: plaintext
    ansible_winrm_scheme: http
    ethernet_adapter: "Ethernet"
    host_ip: "10.10.10.6"
    dns_server: "10.10.10.5"
    vm_name: mad_krillin

  roles:
    - role: disable_rtm
    - role: windows_ip
    - role: activate_windows_srv
    - role: joindomain
    - role: vulnerable_service
    - role: install_office
    - role: hacking_tools
    - role: local_admin_password
  tasks:
  - name: KRILLIN | Ensure user Auditor is present
    ansible.windows.win_user:
      name: auditor
      password: PassW0rd
      state: present
      groups:
        - Users
        - Remote Desktop Users

  - name: KRILLIN | Set SeShutdownPrivilege to User
    win_shell: .\Set-UserRights.ps1 -AddRight -Username auditor -UserRight SeShutdownPrivilege
    args:
      chdir: c:\setup\
    vars:
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: "vagrant"
      ansible_become_password: "vagrant"

  - name: KRILLIN | Become sql_svc a Local Administrator 
    ansible.windows.win_group_membership:
      name: Administrators
      state: present
      members:
        - capsulecorp\vuln_svc
