---
- hosts: tien
  gather_facts: True
  vars:
    ansible_winrm_transport: plaintext
    ansible_winrm_scheme: http
    ethernet_adapter: "Ethernet 2"
    host_ip: "10.10.10.9"
    dns_server: "10.10.10.5"
    vm_name: mad_tien

  roles:
  - role: disable_rtm
  - role: windows_ip
  - role: activate_windows_wks
  - role: install_office
  - role: joindomain
  - role: disable_vagrant_user
  - role: local_admin_password

  tasks:
  - name: TIEN | Install AD WindowsCapability
    win_shell: Add-WindowsCapability -Online -Name 'Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0'
    vars:
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: "vagrant"
      ansible_become_password: "vagrant"

  - name: TIEN | Become employee1 a Local Administrator 
    ansible.windows.win_group_membership:
      name: Administrators
      state: present
      members:
        - capsulecorp\employee1

  - name: TIEN | Ensure user1 profile is present
    community.windows.win_user_profile:
      username:  employee1@capsulecorp
      state: present

  - name: TIEN | Create README.txt
    win_copy:
      dest: C:\Users\employee1\Desktop\README.txt
      content: |
        Take into account that that Real-Time protection and Tamper protection are enabled, so disable them before trying to download any kind of software that can be considered as malware on the machine.
      